name: CI

on:
  push:
    branches: [ '**' ]
    
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install npm dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build the engine
        run: yarn build
